name: Cypress test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install
      - name: Install Cypress
        run: yarn add cypress --dev
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js
